{
    "extends": ["plugin:prettier/recommended"],
    "plugins": ["prettier"],

    "env": { "es6": true, "browser": true, "jest": true, "node": true },
    "parserOptions": { "ecmaVersion": 2022 }
}
