version: "3.3"
services:
  node:
    restart: always
    build: .
    ports:
      - "6234:6234"
    depends_on:
      - mysql
    volumes:
      - ~/.dfcsv:/csv
    
  mysql:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
